# Generated by Django 5.0.2 on 2026-03-19 11:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_sale_saleitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='bought_price',
            new_name='buying_price',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='sale_price',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='stockmovement',
            old_name='unit_price',
            new_name='buying_price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='stockanalytics',
            name='total_stock_value',
        ),
        migrations.AddField(
            model_name='material',
            name='buying_price',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Purchase price from supplier', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=2, help_text='Selling price to customers', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockanalytics',
            name='total_potential_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stockanalytics',
            name='total_stock_value_at_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stockanalytics',
            name='total_stock_value_at_selling',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
