# Generated by Django 5.0.2 on 2026-04-01 07:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_bought_price_saleitem_buying_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A descriptive name for the order (e.g., 'Monthly Cement Order')", max_length=200, verbose_name='Order Name')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Order Number')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField()),
                ('actual_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received by Supplier'), ('ACCEPTED', 'Accepted by Supplier'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='inventory.supplier')),
            ],
            options={
                'db_table': 'supplier_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the material ordered', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price of the material at the time of ordering', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost (quantity * unit_price)', max_digits=15)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Quantity received so far', max_digits=12)),
                ('is_received', models.BooleanField(default=False, help_text='Whether the full quantity has been received')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this item')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_items', to='inventory.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.supplierorder')),
            ],
            options={
                'db_table': 'supplier_order_items',
                'ordering': ['-id'],
            },
        ),
    ]
