# Generated by Django 5.0.2 on 2026-04-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_supplierorder_supplierorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry Date'),
        ),
    ]
