# Generated by Django 6.0.6 on 2026-06-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_material_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('WAREHOUSE', 'Warehouse Staff'), ('STOREKEEPER', 'Storekeeper'), ('ACCOUNTANT', 'Accountant')], default='WAREHOUSE', max_length=20),
        ),
    ]
