# Generated by Django 6.0.6 on 2026-06-23 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='accountant_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='accountant_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='accountant_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviewed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='accountant_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
